function [] =...
    call_exp_fit_resonance_cases(qdexp,clbrsr,filepathexp,col,lst,plotdata,temps,row,tempsmc,...
    sb,fca,torb,colabs,sampletemp,modelst,modes)

if strcmpi(qdexp,'Yes')
    call_exp_fit(lst,plotdata,temps,row,tempsmc,sb,fca,torb,colabs,sampletemp,modelst,...
         col,clbrsr)
end